### ISSUE TITLE
normalize.css not in components/

### ISSUE THREAD

**Issue by miduku** [toddmotto/fireshell#73]
I am fairly new to Grunt & Bower and am trying to understand how fireshell works but I can't quite seem to get why ``normalize-css/normalize.css`` isn't appearing in the ``components/`` folder.

#27 and #32 are suppose to manage normalize trough bower, as in download the latest build from necolas's build, right?... well that's what I think I understand.

The problem is that when I run ``grunt-dev.bat`` for the first time bower doesn't get the file but everything else seems to work.
Am I missing or misunderstanding something? Do I have to add it manually into the folder?

```
Bower 1.2.8
Node 0.12.7
Windows 7 x64
```

**Comment by miduku** [comment]
I've found out that apparently I get an error with with the postinstall script  ``bower install`` and I find this in my ``npm-debug.log``

```
...
40850 info linkStuff fireshell@1.1.0
40851 silly linkStuff fireshell@1.1.0 has C:\Users\miduku\Desktop as its parent node_modules
40852 verbose linkBins fireshell@1.1.0
40853 verbose linkMans fireshell@1.1.0
40854 verbose rebuildBundles fireshell@1.1.0
40855 verbose rebuildBundles [ '.bin',
40855 verbose rebuildBundles   'bower',
40855 verbose rebuildBundles   'connect-livereload',
40855 verbose rebuildBundles   'grunt',
40855 verbose rebuildBundles   'grunt-autoprefixer',
40855 verbose rebuildBundles   'grunt-bower',
40855 verbose rebuildBundles   'grunt-contrib-clean',
40855 verbose rebuildBundles   'grunt-contrib-concat',
40855 verbose rebuildBundles   'grunt-contrib-connect',
40855 verbose rebuildBundles   'grunt-contrib-cssmin',
40855 verbose rebuildBundles   'grunt-contrib-jshint',
40855 verbose rebuildBundles   'grunt-contrib-sass',
40855 verbose rebuildBundles   'grunt-contrib-uglify',
40855 verbose rebuildBundles   'grunt-contrib-watch',
40855 verbose rebuildBundles   'grunt-open',
40855 verbose rebuildBundles   'matchdep' ]
40856 info install fireshell@1.1.0
40857 info postinstall fireshell@1.1.0
40858 verbose unsafe-perm in lifecycle true
40859 info fireshell@1.1.0 Failed to exec postinstall script
40860 verbose stack Error: fireshell@1.1.0 postinstall: `bower install`
40860 verbose stack Exit status 1
40860 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
40860 verbose stack     at EventEmitter.emit (events.js:110:17)
40860 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
40860 verbose stack     at ChildProcess.emit (events.js:110:17)
40860 verbose stack     at maybeClose (child_process.js:1015:16)
40860 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
40861 verbose pkgid fireshell@1.1.0
40862 verbose cwd C:\Users\miduku\Desktop\web2
40863 error Windows_NT 6.1.7601
40864 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
40865 error node v0.12.7
40866 error npm  v2.11.3
40867 error code ELIFECYCLE
40868 error fireshell@1.1.0 postinstall: `bower install`
40868 error Exit status 1
40869 error Failed at the fireshell@1.1.0 postinstall script 'bower install'.
40869 error This is most likely a problem with the fireshell package,
40869 error not with npm itself.
40869 error Tell the author that this fails on your system:
40869 error     bower install
40869 error You can get their info via:
40869 error     npm owner ls fireshell
40869 error There is likely additional logging output above.
40870 verbose exit [ 1, true ]
```

Does anyone else have this problem?

**Comment by miduku** [comment]
I seem to have found the problem, which were some dependencies issues. I changed some versioning syntax (#74) to get the latest build and now it works fine. 

Hope this helps.
